### ISSUE TITLE
Printing parameter files with "neg"

### ISSUE THREAD

**Issue by peonor** [ericchansen/q2mm#11]
"parameters.py" still does not print a parameter list with "neg" for parameters that are allowed to be negative. I made a simple change at the end, shown here as "diff" output between original and my new file:

252c252,254
<             print('{} {}'.format(param.mm3_row, param.mm3_col))
---
>             if param.allow_negative:
>                 print('{} {} neg'.format(param.mm3_row, param.mm3_col))
>             else: print('{} {}'.format(param.mm3_row, param.mm3_col))

**Comment by ericchansen** [comment]
This seems odd to me. The current version of parameters.py has 

```
    # Print the parameters.                                                                               
    if opts.printparams:
        for param in params:
            if param.ptype in ['df', 'q']:
                print('{} {} neg'.format(param.mm3_row, param.mm3_col))
            else:
                print('{} {}'.format(param.mm3_row, param.mm3_col))
```

This does place the keyword "neg" after dihedrals and charge parameters for me.

Nonetheless, saying `if param.allow_negative` makes more sense, so I'll make that change.

**Comment by peonor** [comment]
So obviously I'm not using the latest code. This will work better when I can get our git talk to GitGub...
/Per-Ola

Sent from my iPhone

On 9 okt. 2015, at 16:36, Eric Hansen <notifications@github.com<mailto:notifications@github.com>> wrote:


This seems odd to me. The current version of parameters.py has

    # Print the parameters.
    if opts.printparams:
        for param in params:
            if param.ptype in ['df', 'q']:
                print('{} {} neg'.format(param.mm3_row, param.mm3_col))
            else:
                print('{} {}'.format(param.mm3_row, param.mm3_col))


This does place the keyword "neg" after dihedrals and charge parameters for me.

Nonetheless, saying if param.allow_negative makes more sense, so I'll make that change.

-
Reply to this email directly or view it on GitHub<https://github.com/ericchansen/q2mm/issues/11#issuecomment-146890206>.

________________________________

Confidentiality Notice: This message is private and may contain confidential and proprietary information. If you have received this message in error, please notify us and remove it from your system and note that you must not copy, distribute or take any action in reliance on it. Any unauthorized use or disclosure of the contents of this message is not permitted and may be unlawful.
