### ISSUE TITLE
Input for compare.py and loop.py

### ISSUE THREAD

**Issue by arosale4** [ericchansen/q2mm#17]
I've been using the sort branch and I want to clarify how it works. I think I misunderstood the commit message (commit 1434d4d43c7d115799b3b9fdc13fbf78bc28f5ac), but what needs to be done is that the input for compare and loop have to be in order of datatype. Can this be clarified?

So this will work:
python compare.py -c " -d somedirc/ -me -mea -meo -meao -mb -ma -mt -mq -mqh -mqa -mh -mgeig" -r "  -d somedirc/ -je -jea -jeo -jeao -jb -ja -jt -jq -jqh -jqa -jh -jgeig"

where as if I were to switch the orders of the datatypes it will not be compared appropriately.

So this will not work, where I have moved angle and torsions to the end of the line:
python compare.py -c " -d somedirc/ -me -mea -meo -meao -mb -mq -mqh -mqa -mh -mgeig **-ma -mt** " -r "  -d somedirc/ -je -jea -jeo -jeao -jb -jq -jqh -jqa -jh -jgeig **-ja -jt**"

**Comment by arosale4** [comment]
Additionally, as long as you keep the same order within the calculate and reference datatype it will compare the right data.
Both of these should work:
python compare.py -c " -d somedirc/ -me file1 file2" -r " -d somedirc/ -je file1 file2"
python compare.py -c " -d somedirc/ -me file2 file1" -r " -d somedirc/ -je file2 file1"

Again can this be confirmed?

**Comment by ericchansen** [comment]
> So this will work:
> python compare.py -c " -d somedirc/ -me -mea -meo -meao -mb -ma -mt -mq -mqh -mqa -mh -mgeig" -r " -d somedirc/ -je -jea -jeo -jeao -jb -ja -jt -jq -jqh -jqa -jh -jgeig"
> 
> where as if I were to switch the orders of the datatypes it will not be compared appropriately.
> 
> So this will not work, where I have moved angle and torsions to the end of the line:
> python compare.py -c " -d somedirc/ -me -mea -meo -meao -mb -mq -mqh -mqa -mh -mgeig -ma -mt " -r " -d somedirc/ -je -jea -jeo -jeao -jb -jq -jqh -jqa -jh -jgeig -ja -jt"

Actually, both of these will work. The calculate module creates a list of Datum objects, and these objects are always added in the following order: -r, -je, -ge, -me, -jea, -gea, -mea, -jeo, -geo, meo, -jeao, -geao, -meao, -jb, -mb, -ja, -ma, -jt, -mt, -jq, -mq, -jqh, -mqh, -jqa, -mqa, -jh, -gh, -mh, -jeigz, -geigz, -mjeig, -mgeig (hope I didn't miss any on that skim through calculate.py). You can also look through calculate.py to see the order. I tried to make it fairly clear with all capital comments.

> Additionally, as long as you keep the same order within the calculate and reference datatype it will compare the right data.
> Both of these should work:
> python compare.py -c " -d somedirc/ -me file1 file2" -r " -d somedirc/ -je file1 file2"
> python compare.py -c " -d somedirc/ -me file2 file1" -r " -d somedirc/ -je file2 file1"

This is the important part, and yes, both of those will work. However,

```
python compare.py -c " -d somedirc -me file1 file2" -r " -d somedirc -je file2 file1"
```

will not align the data properly.

**Comment by arosale4** [comment]
You are correct, you should have to specify the datatype order. There were some sort commands that were left un-commented in compare.py. It may be beneficial to still put them in that order, for "just in case" measures.

**Comment by ericchansen** [comment]
Hmm those uncommented sort commands may mess things up. Thanks for catching that. I'll look into that.
