### ISSUE TITLE
Setup esp

### ISSUE THREAD

**Issue by nberkel05** [ericchansen/q2mm#18]
When I'm running this it works fine except it's not selecting all the atoms I want it to. What would be nice is to only deselect atoms from OPT substructures. Instead, it's also deselecting atoms from a random P-H and the Rhodium substructure I have.

[ferrocene_setupesp.zip](https://github.com/ericchansen/q2mm/files/280225/ferrocene_setupesp.zip)

**Comment by ericchansen** [comment]
This was corrected in 40ade24ad62f48fd6b47, which is currently only on the sort branch. Until I'm done testing, you can checkout that branch and use its version of [setup_esp.py](https://github.com/ericchansen/q2mm/blob/sort/setup_esp.py).
