### ISSUE TITLE
error with get_most_converged.py

### ISSUE THREAD

**Issue by arosale4** [ericchansen/q2mm#4]
I have tried two different commands and had two different errors. I am trying to get the most converged coordinates from a Gaussian log. 
Here is the first command:
    python get_most_converged.py ../complex_substrates/allyl_alcohol_ts1b_re.log -c both -f gauss
Output:
    Traceback (most recent call last):
         File "get_most_converged.py", line 34, in <module>
               output = best_strucutre.format_coords (format=opts.format)
    AttributeError: 'NoneType' object has no attribute 'formate_coords)

Second Command
    python get_most_converged.py ../complex_substrates/allyl_alcohol_ts1b_re.log -a -c both -f gauss
Output:
    Traceback (most recent call last):
         File "get_most_converged.py", line 27, in <module>
               output = best_strucutre.format_coords (format=opts.format)
         File "/afs/crc.nd.edu/user/a/arosale4/q2mm/filteypes.py", line 681, in format_coords
               elements[atom.atomic_num, atom.x, atom.y, atom.z))
     KeyError: 46

**Comment by ericchansen** [comment]
I never wanted get_most_converged.py to be a script in itself. It was just an ends to a means.

Right now I am working on a large overhaul of many parts of the code, so I don't necessarily want to make too many changes to the old version, as I'd just have to translate them over anyway.

What has to be done is inside the GaussLog class in filetypes.py. The search that parses through the log could be modified to pick up more coordinate sections. I think that right now it searches for particular keywords in the log that indicate the start and end of the geometry optimization section, and everything on lines that aren't between those keywords is ignored. If you just got rid of that check for the keywords, I think the existing regex could pick up the coordinates you need.

What I'm going to do is dig up a really old version of the code that I have. In that code, I read the archive section of the Gaussian log for data, which I'd like to implement again. The archive section should always contain the most recent coordinates.

I will update this issue when there's a working solution. Feel free to tackle it yourself if you're bored.
