### ISSUE TITLE
Charge fitting

### ISSUE THREAD

**Issue by peonor** [ericchansen/q2mm#7]
There is a problem when fitting dipoles at the border of the parameterization region, that is, when charges are affected both by dipoles that change, and unmodified dipoles from the underlying force field. Could potentially be alleviated by pruning the data:

Include all charges and charges_with_H where all dipoles to that atom are being modified.
For any atom with at least one unmodified bond to a non-hydrogen atom, exclude the charge.
For an atom that has only bonds that are being modified, and bonds to hydrogens, include the charges_with_H in the data set, but not the regular partial charge.

**Comment by ericchansen** [comment]
Issue #7 resolved.

See commits 83a7175c0cc, 1bb579f04dbe, and f2e57cd2c825e7b.
